# Generated by Django 5.2 on 2025-04-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_uniformes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallavariante',
            name='imagen',
        ),
    ]
