# Generated by Django 5.2 on 2025-04-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_uniformes', '0002_remove_tallavariante_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VarianteProducto',
        ),
    ]
